openapi: 3.0.0

info:
  title: Otters API
  description: Documentación OpenAPI
  version: "1.0"
  contact:
    name: Pedro Allue
    email: pedro.allue.tamargo@gmail.com

servers:
  - url: http://localhost:8080
    description: Localhost development server

tags:
  - name: "User"
    description: "Everithing about the users"
  - name: "Sanitary Zone"
    description: "Sanitary Zones"

paths:
  /user:
    # Get users
    get:
      tags:
        - "User"
      description: Get all users
      summary: Get all users

      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/user"
    # Create user
    post:
      tags:
        - "User"
      description: Create a new user
      requestBody:
        description: Información del usuario. El campo _id será ignorado.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/user"

      responses:
        "201":
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"

  /user/{uid}:
    # Get specific user
    get:
      tags:
        - "User"
      description: Get an user with uid
      summary: Get an user with uid
      parameters:
        - in: path
          name: uid
          description: UID of the user
          required: true
          schema:
            type: string
      responses:
        "200":
          description: User exists
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"
        "404":
          description: User does not exist
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"

    # Deletes specific user
    delete:
      tags:
        - "User"
      description: Deletes an user with _id = uid
      summary: Deletes an user with _id = uid
      parameters:
        - in: path
          name: uid
          description: UID of the user
          required: true
          schema:
            type: string
      responses:
        "200":
          description: User deleted successfully
          content:
            application/json:
              schema:
                type: string
                example: ok
        "404":
          description: User doesn't exit
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"

  # User's petitions
  /user/{uid}/petitions:
    get:
      tags:
        - "User"
      description: Get all the petitions of the user uid
      summary: Get user's petitions with an uid
      parameters:
        - in: path
          name: uid
          description: UID of the user
          required: true
          schema:
            type: string
      responses:
        "200":
          description: User exists
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/petitions"
        "404":
          description: User does not exist
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
    # Add a petition
    post:
      tags:
        - "User"
      description: Add new petition to the user with _id = uid
      summary: Add new petition to the user
      requestBody:
        description: Info about the petition. 
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/petitions"

      responses:
        "201":
          description: Petition created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/petitions"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
        "404":
          description: User does not exist
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
  
  # Operations over a specific petition              
  /user/{uid}/petitions/{petitionId}:
    get:
      tags:
        - "User"
      description: Get a petition with _id = locationId of the user uid
      summary: Get a specific petition
      parameters:
        - in: path
          name: uid
          description: UID of the user
          required: true
          schema:
            type: string
        - in: path
          name: petitionId
          description: ID of the petition
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Petition exists
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/petitions"
        "404":
          description: User or petition does not exist
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
    # Update a petition
    put:
      tags:
        - "User"
      description: Update the petition with _id = locationId of the user uid
      summary: Update a petition of an user
      parameters:
        - in: path
          name: uid
          description: UID of the user
          required: true
          schema:
            type: string
        - in: path
          name: petitionId
          description: ID of the petition
          required: true
          schema:
            type: string
      requestBody:
        description: Info about the new petition. 
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/petitions"

      responses:
        "200":
          description: Petition updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/petitions"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
        "404":
          description: User or petition does not exist
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
    delete:
      tags:
        - "User"
      description: Delete the petition with _id = locationId of the user uid
      summary: Delete a petition of an user
      parameters:
        - in: path
          name: uid
          description: UID of the user
          required: true
          schema:
            type: string
        - in: path
          name: petitionId
          description: ID of the petition
          required: true
          schema:
            type: string

      responses:
        "204":
          description: Petition deleted successfully
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
        "404":
          description: User or petition does not exist
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"              

  # SanitaryZone Routes
  # Get all zones
  /zone:
    get:
      description: Get all sanitary zones
      summary: Get all sanitary zones
      tags:
        - "Sanitary Zone"
      responses:
        "200":
          description: Successfull response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/sanitaryZoneWithoutData"

  # Get a zone given its id
  /zone/{id}:
    get:
      description: Get sanitary zone given id
      summary: Get sanitary zone given id
      tags:
        - "Sanitary Zone"
      parameters:
        - in: path
          name: id
          description: Zone id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successfull response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/sanitayZoneWithData"
        "404":
          description: Zone id not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"

  # Fetch data from remote
  /zone/fetchData:
    get:
      tags:
        - "Sanitary Zone"
      description: Start zone remote source fetch data
      summary: Start zone remote source fetch data
      responses:
        "202":
          description: Successful response. Server is fetching source asynchronously.

  # Get data given id
  /zone/{id}/data:
    get:
      tags:
        - "Sanitary Zone"
      description: Get zone data by id
      summary: Get zone data by id
      parameters:
        - in: path
          name: id
          description: Sanitary zone's id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful response. Data returned
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/sanitaryZoneData"

components:
  schemas:
    # User Schema
    user:
      type: object
      required:
        - "name"
        - "years"
      properties:
        _id:
          type: integer
          description: Object identifier
        name:
          type: string
          description: Name of the user
        years:
          type: integer
          description: Years of the user
        petitions:
          type: array
          description: IDs of the user's petitions
          items: 
            type: string
    # Sanitary Zone Schema
    sanitaryZoneWithoutData:
      title: SanitaryZone
      type: object
      description: Sanitary Zone Schema without data
      required:
        - "name"
        - "updatedAt"
      properties:
        _id:
          type: integer
          description: Object identifier
        name:
          type: string
          description: Name of the sanitary zone
        updatedAt:
          type: string
          format: date
          description: Last date of data update

    sanitayZoneWithData:
      allOf:
        - $ref: "#/components/schemas/sanitaryZoneWithoutData"
        - properties:
            data:
              type: array
              items:
                $ref: "#/components/schemas/sanitaryZoneData"
      title: SanitaryZone
      description: Sanitary Zone Schema with data
      type: object

    # Data of sanitary zone
    sanitaryZoneData:
      type: object
      required:
        - "date"
        - "possitives"
      properties:
        _id:
          type: integer
          description: Object identifier
        date:
          type: string
          format: date
          description: Date of data
        possitives:
          type: integer
          description: Number of possitives at current date
    
    # Petition Schema
    petitions:
      type: object
      required:
        - "title"
        - "body"
        - "place"
        - "isUrgent"
        - "status"

      properties:
        _id:
          type: integer
          description: Object identifier
        title:
          type: string
          description: Title of the petition
        body:
          type: string
          description: A description of the petition
          maxLength: 150
        userId:
          type: string
          description: Petition's owner Id
        place:
          type: string
          description: Place where the petition is located
        isUrgent:
          type: boolean
          description: Indicates if the petition is urgent or not
          default: false
        status: 
          type: string
          description: Status of the petition. It could be 'created', 'cancelled' or 'assigned'

    # Error schema
    error:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: Error Message
